# Generated by Django 6.0.5 on 2026-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom officiel de l'établissement", max_length=200)),
                ('code_mepsa', models.CharField(help_text="Code d'identification MEPSA (ex: BZV-CEG-001, PNR-LEG-012)", max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PUBLIC', 'Établissement public (État)'), ('PRIVE_CONV_I', 'Privé conventionné Type I — subventionné'), ('PRIVE_CONV_II', 'Privé conventionné Type II — partiellement subventionné'), ('PRIVE_NON_CONV', 'Privé non conventionné'), ('CONFESSIONNEL', 'Établissement confessionnel'), ('TECHNIQUE', 'Établissement technique / professionnel (LTP/CFP)')], default='PUBLIC', help_text="Catégorie juridique et financière de l'établissement", max_length=30)),
                ('cycles', models.CharField(help_text="Cycles enseignés, séparés par des virgules (ex: 'PRIMAIRE,COLLEGE')", max_length=100)),
                ('region', models.CharField(help_text='Région (Brazzaville, Pointe-Noire, Niari, etc.)', max_length=50)),
                ('district', models.CharField(blank=True, help_text='District / Arrondissement', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Établissement opérationnel')),
                ('date_ouverture', models.DateField(blank=True, help_text='Date de création officielle', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Établissement scolaire',
                'verbose_name_plural': 'Établissements scolaires',
                'ordering': ['region', 'nom'],
                'indexes': [models.Index(fields=['code_mepsa'], name='ecoles_ecol_code_me_e05957_idx'), models.Index(fields=['type', 'is_active'], name='ecoles_ecol_type_8a154e_idx'), models.Index(fields=['region'], name='ecoles_ecol_region_4fce58_idx')],
            },
        ),
    ]
