# Generated by Django 6.0.5 on 2026-05-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom usuel de la classe (ex: 6ème A, CM2 1, Terminale L)', max_length=50)),
                ('niveau', models.CharField(choices=[('PS', 'Préscolaire - Petite Section'), ('MS', 'Préscolaire - Moyenne Section'), ('GS', 'Préscolaire - Grande Section'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2NDE', '2nde'), ('1ERE', '1ère'), ('TLE', 'Terminale')], help_text='Niveau officiel MEPSA', max_length=10)),
                ('capacite_max', models.PositiveIntegerField(default=45, help_text='Effectif maximum recommandé par la circulaire MEPSA')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(help_text='Établissement auquel appartient cette classe', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.ecole')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['ecole__nom', 'niveau', 'nom'],
                'indexes': [models.Index(fields=['niveau', 'is_active'], name='ecoles_clas_niveau_8286f7_idx'), models.Index(fields=['ecole', 'is_active'], name='ecoles_clas_ecole_i_767f25_idx')],
                'constraints': [models.UniqueConstraint(fields=('nom', 'ecole'), name='unique_classe_par_ecole')],
            },
        ),
    ]
