# Generated by Django 6.0.5 on 2026-06-16 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0002_classe'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Code MEPSA (ex: MATH6, FR3, HIST4)', max_length=20, unique=True)),
                ('coefficient_defaut', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er Trimestre (Septembre → Décembre)'), (2, '2ème Trimestre (Janvier → Mars)'), (3, '3ème Trimestre (Avril → Juin/Juillet)')])),
                ('type_eval', models.CharField(choices=[('INT', 'Interrogation / Contrôle continu'), ('DEV', 'Devoir surveillé'), ('EXA', 'Examen de fin de trimestre'), ('TP', 'Travaux Pratiques (Enseignement technique)')], max_length=3)),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note_sur_20', models.DecimalField(decimal_places=2, help_text='Note sur 20, au centième', max_digits=4)),
                ('date_eval', models.DateField()),
                ('est_validee', models.BooleanField(default=False, help_text='Verrouillée après conseil de classe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='ecoles.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogie.matiere')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-date_eval'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'matiere', 'trimestre', 'type_eval'), name='unique_eval_par_eleve_matiere_trim_type')],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er Trimestre (Septembre → Décembre)'), (2, '2ème Trimestre (Janvier → Mars)'), (3, '3ème Trimestre (Avril → Juin/Juillet)')])),
                ('statut', models.CharField(choices=[('PRE', 'Présent'), ('ABS', 'Absent non justifié'), ('EXC', 'Absent justifié (certificat médical, etc.)'), ('RET', 'Retard')], max_length=3)),
                ('justification', models.TextField(blank=True, help_text='Motif ou référence certificat', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecoles.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eleves.eleve')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trimestre', 'statut'], name='pedagogie_p_trimest_af01f2_idx'), models.Index(fields=['eleve', 'trimestre'], name='pedagogie_p_eleve_i_8fc0c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'date'), name='unique_presence_par_jour')],
            },
        ),
    ]
