# Generated by Django 6.0.5 on 2026-05-10 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text="ID unique de l'appareil client (UUID généré côté PWA/mobile)", max_length=100)),
                ('client_operation_id', models.UUIDField(help_text='ID idempotent généré par le client pour éviter les doublons en cas de retry réseau', unique=True)),
                ('operation_type', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10)),
                ('model_name', models.CharField(help_text="Nom du modèle Django cible (ex: 'eleves.Eleve', 'pedagogie.Note')", max_length=50)),
                ('payload', models.JSONField(help_text="Données brutes de l'opération (JSON sérialisé)")),
                ('status', models.CharField(choices=[('PENDING', 'En attente de traitement'), ('PROCESSED', 'Traitée avec succès'), ('CONFLICT', 'Conflit détecté (server_wins)'), ('ERROR', 'Erreur de validation')], db_index=True, default='PENDING')),
                ('conflict_details', models.JSONField(blank=True, help_text='Détails du conflit si server_wins', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération de synchronisation',
                'verbose_name_plural': 'File de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_version', models.JSONField(help_text='Données envoyées par le client')),
                ('server_version', models.JSONField(help_text='Données actuelles en base')),
                ('resolution', models.CharField(default='server_wins', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncqueue')),
            ],
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['device_id', 'status'], name='sync_syncqu_device__14bea7_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['client_operation_id'], name='sync_syncqu_client__390958_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['user', 'created_at'], name='sync_syncqu_user_id_fb8e64_idx'),
        ),
    ]
