# Generated by Django 6.0.5 on 2026-05-12 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0002_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_mepsa', models.CharField(help_text='Identifiant national MEPSA (ex: M2026-BZV-004521)', max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TRANSFERE', 'Transféré vers un autre établissement'), ('EXCLU', 'Exclu / Abandon scolaire'), ('DIPLOME', 'Diplômé')], default='ACTIF', max_length=20)),
                ('est_redoublant', models.BooleanField(default=False, help_text='A déjà redoublé au moins une fois')),
                ('historique_redoublements', models.JSONField(blank=True, default=list, help_text="Historique structuré : [{'classe': '6ème A', 'annee': '2024-2025', 'moyenne': 8.5}]")),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('vaccinations_a_jour', models.BooleanField(blank=True, help_text='Carnet vérifié (obligatoire CP1)', null=True)),
                ('notes_medicales', models.TextField(blank=True, help_text='Allergies, asthme, régime spécial, handicaps')),
                ('is_active', models.BooleanField(default=True, help_text="Élève actif dans l'établissement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_inscrits', to='ecoles.classe')),
                ('ecole', models.ForeignKey(help_text="Établissement d'inscription", on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='ecoles.ecole')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='LienFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('SIBLING', 'Frère/Sœur majeur responsable'), ('AUTRE', 'Autre responsable désigné')], max_length=10)),
                ('est_responsable_financier', models.BooleanField(default=False, help_text='Prend en charge les frais scolaires')),
                ('est_contact_principal', models.BooleanField(default=True, help_text='Reçoit SMS/WhatsApp prioritaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien familial',
                'verbose_name_plural': 'Liens familiaux',
                'unique_together': {('eleve', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(related_name='enfants', through='eleves.LienFamille', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['matricule_mepsa'], name='eleves_elev_matricu_6f920a_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['ecole', 'statut'], name='eleves_elev_ecole_i_5a5ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['genre', 'classe_actuelle'], name='eleves_elev_genre_7aad79_idx'),
        ),
    ]
