# Generated by Django 6.0.5 on 2026-06-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_candidat', models.CharField(help_text='Numéro de table/convocation officiel', max_length=30, unique=True)),
                ('centre_examen', models.CharField(help_text="Lieu de passage de l'examen", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures_examens', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Candidat',
                'ordering': ['session', 'numero_candidat'],
            },
        ),
        migrations.CreateModel(
            name='ResultatFinal',
            fields=[
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resultat', serialize=False, to='examens.candidatexamen')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('mention', models.CharField(choices=[('PASS', 'Passable (10-11,99)'), ('AB', 'Assez Bien (12-13,99)'), ('B', 'Bien (14-15,99)'), ('TB', 'Très Bien (≥16)'), ('AJ', 'Ajourné (<10)'), ('ADM', 'Admis (mention non spécifiée)')], editable=False, max_length=5)),
                ('est_admis', models.BooleanField(default=False)),
                ('date_proclamation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Résultat final',
            },
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2025-2026', max_length=9)),
                ('type_examen', models.CharField(choices=[('CEPE', "CEPE + Concours d'entrée en 6ème"), ('BEPC', "BEPC (Brevet d'Études du 1er Cycle)"), ('BAC_GEN', 'Baccalauréat Général'), ('BAC_TECH', 'Baccalauréat Technique'), ('BAC_PRO', 'Baccalauréat Professionnel')], max_length=20)),
                ('serie', models.CharField(blank=True, choices=[('L', 'Littéraire'), ('S', 'Scientifique'), ('ST', 'Sciences & Technologies'), ('SE', 'Sciences Économiques')], max_length=5, null=True)),
                ('statut', models.CharField(choices=[('PREP', 'Préparation / Inscriptions ouvertes'), ('COURS', 'Examens en cours'), ('SAISIE', 'Saisie des notes'), ('PROC', 'Résultats proclamés'), ('FERME', 'Session clôturée')], default='PREP')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_proclame', models.BooleanField(default=False, help_text='Résultats officiels validés par le jury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Session d'examen",
                'ordering': ['-annee_scolaire', 'type_examen'],
                'constraints': [models.UniqueConstraint(fields=('annee_scolaire', 'type_examen', 'serie'), name='unique_session_par_annee_type_serie')],
            },
        ),
        migrations.AddField(
            model_name='candidatexamen',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='examens.sessionexamen'),
        ),
        migrations.CreateModel(
            name='NoteExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(help_text="Nom officiel de l'épreuve (ex: Mathématiques, SVT)", max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=3)),
                ('note', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='examens.candidatexamen')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Note d'examen",
                'ordering': ['candidat', 'matiere'],
                'constraints': [models.UniqueConstraint(fields=('candidat', 'matiere'), name='unique_note_par_candidat_matiere')],
            },
        ),
    ]
