# Generated by Django 6.0.5 on 2026-05-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('ecoles', '0002_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.ForeignKey(blank=True, help_text='Établissement de rattachement principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='ecoles.ecole'),
        ),
    ]
